# Building (não mexa a menos que saiba o que está fazendo)
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENCE.txt', 'CNAME']


# Parâmetros do site
title: "Scrumday 2018"
email: "contato@scrumday.com.br"
description: "Ótima oportunidade para indivíduos, equipes e gerentes aumentarem seu sucesso na busca por mais agilidade e melhor desenvolvimento de software."
baseurl: "/scrum-day-short"
url: "https://barbaromatrix.github.io/"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-54405211-1"
googleAnalyticsSiteUrl: "gdg-x.github.io"

# Informações dos organizadores
organizerName: "Concrete Solutions"
organizerAlternateName: "Concrete Solutions"
organizerDescription: "Comunidade aberta e voluntária que estuda, cria e dissemina tecnologias e desenvolvimento ágil em Belém do Pará."
organizerEmail: "contato@scrumday.com.br"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://www.scrumday.com.br/"

# Metadados para a página
metaKeywords: "concrete, scrum, scrumDay, SCRUMDAY, evento scrum, brasil, concrete solutions, agil, trilha"
twitterAccount: "@tasafo"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documentos-chave
c4pUrl: "https://docs.google.com/forms/d/1PucWMWW3v6eGz9RQW0_q13cob45yOj6pgQ5uyq0EzYs/viewform?c=0&w=1&usp=mail_form_link"
c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"

# Navegação
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/schedule/", text: "Agenda"}
#  - {permalink: "/speakers/", text: "Palestrantes"}
#  - {permalink: "/team/", text: "Equipe"}
#  - {permalink: "/logistics/", text: "Logística"}
bottomNavigationLinks:
 - {link: "https://docs.google.com/forms/d/1PucWMWW3v6eGz9RQW0_q13cob45yOj6pgQ5uyq0EzYs/viewform?c=0&w=1&usp=mail_form_link", text: "Submeta sua palestra"}
rightNavigationButtons:
 - {link: "http://www.eventick.com.br/devfest-norte-2014", text: "Inscreva-se!"}

# Bloco "Hero"
heroTitle: "Scrum Day <typeout> 2018"
eventDate: "8 de junho de 2018"
typeoutTextValues: '"", "| Palestras", "| Workshops"'
typeoutFallback: "Temporada"
heroButtons:
 - {url: "https://docs.google.com/forms/d/1PucWMWW3v6eGz9RQW0_q13cob45yOj6pgQ5uyq0EzYs/viewform?c=0&w=1&usp=mail_form_link", text: "Seja um palestrante"}

# Bloco "Sobre"
aboutTitle: "Sobre o evento"
aboutBlock:
 - {title: "Palestras Inspiradoras", image: "conference.jpg", text: "O maior evento de tecnologias Google no norte do Brasil, conduzido por pessoas engajadas das comunidades GDG de Belém, Manaus e São Luís!  Temas interessantes, ótimos palestrantes e muita diversão!" }
 - {title: "Scrum talks", image: "hackathon.jpg", text: "Quer acumular experiência e resolver problemas do mundo real passando um dia trocando ideias e programando com pessoas que fazem a diferença?  Conheça e aprenda mais com Android Wear com práticas mão-na-massa." }
 - {title: "Workshops", image: "workshop.jpg", text: "Amplie sua rede de networking trocando experiências e muita informação com grandes nomes das comunidades regionais de tecnologia, tudo isso num ambiente leve energizado e descontraído." }

# Bloco "Estatísticas"
statisticBlock:
 - {count: "05", specialCharacter: "", info: "workshops práticos", detail: ""}
 - {count: "03", specialCharacter: "", info: "scrum talks", detail: ""}
 - {count: "21", specialCharacter: "", info: "Apresentações", detail: ""}
 - {count: "02", specialCharacter: "", info: "Keynotes de renome", detail: ""}

# Bloco "Últimas Notícias"
latestNewsTitle: "Ultimas notícias"

# Bloco "Palestrantes Rockstar"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Keynotes e Palestrantes"
rockstarSpeakersButtonText: "Veja todos os palestrantes"

# Bloco "Localização"
locationBlockTitle: "Local"
eventLocationName: "Centro de Convenções SENAC"
eventLocationLink: "http://www.computerhall.com.br/hall/"
eventStreetAddress: "Engenheiro Eusébio Stevaux, 823 Prédio 2"
eventAddressLocality: "Jurubatuba"
eventAddressLocalityRegion: "São Paulo"
eventPostalCode: "04696-000"
eventAddressCountry: "Brasil"
eventStartTime: "2018-06-08T09:00"
eventDoorTime: "09:00"
eventEndTime: "2018-06-08T18:00"
eventPlaceCoordinates: "-23.6698635,-46.7022156"
mapCenterCoordinates: "-23.6698635,-46.7022156"
mapMobileCenterCoordinates: "-23.6698635,-46.7022156"

# Bloco "Venue"
venueBlockTitle: "Local"
venueTitle: "Computer Hall"
venueFeatures: ["Auditório duplo com capacidade total para 580 lugares", "6 salas de eventos", "Acesso facilitado no centro da cidade"]

# Bloco "Tweets"
tweetsFeedTitle: "O que está rolando?"
twitterHashTag: "devfestnorte"
# twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=900"

# Bloco "Parceiros"
organizersTitle: "Organizadores"
partnersTitle: "Apoio"

# Bloco "Subscreva-se"
subscribeTitle: "Subscreva-se para novidades"
subscribeAction: "http://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Registre-se até a data do evento. Vagas limitadas. Fique ligado!"

# Bloco "Tíquetes"
ticketsTitle: "Inscreva-se"
ticketsInfo: "Inscrições dão acesso a todas as trilhas de palestras, material do evento e coffee-breaks. Almoço e despesas com happy-hour não inclusas."
ticketsOffers:
 -
  name: "EARLY BIRD"
  price: "R$ 380,00"
  priceCurrency: "BRL"
  ticketsNumber: "50"
  buyButtonLink: "https://www.eventbrite.com.br/e/scrum-day-2018-tickets-41630743675"
  buyButtonText: "Faça sua inscrição!"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2018-05-01T00:00"
  validThrough: "2018-06-01T12:00"
  disabled: false
 -
  name: "REGULAR"
  price: "R$ 480,00"
  priceCurrency: "BRL"
  ticketsNumber: "50"
  buyButtonLink: "https://www.eventbrite.com.br/e/scrum-day-2018-tickets-41630743675"
  buyButtonText: "Garanta o seu!"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-10-16T00:00"
  validThrough: "2014-11-01T12:00"
  disabled: true

# Rodapé
socialLinks:
 - {link: "https://plus.google.com/101017820294431097315", icon: "google-plus"}
 - {link: "https://twitter.com/devfestnorte", icon: "twitter"}
 - {link: "https://www.facebook.com/pages/DevFest-Norte/263072717236314", icon: "facebook"}
 # - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   # - {link: "http://gdg.org.ua", text: "GDG.org.ua"}
   - {link: "https://developers.google.com", text: "Google Developers"}
 -
  title: "Contatos"
  links:
   - {link: "mailto:devfestnorte.org@gmail.com", text: "Escreva-nos"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Código de Conduta"}

# Blog
blogTitle: "Últimas notícias"
blogCommentsEnabled: true
discusShortName: "devfestnorte"

# Bloco "Lista de Palestrantes"
showSessions: true
thumbnailsFolder: /img/speakers/

# Bloco "Equipe"
teamBlockTitle: "Quem somos"
aboutUs: "Ferramentas e produtos do Google se tornaram sinônimo de produtividade e desempenho no mundo online. O número de inovações tecnológicas e indústrias de TI em que o Google está criando novas ferramentas e produtos é enorme. É difícil conhecer todos eles. É por isso que as pessoas começaram a se reunir em pequenos grupos locais e partilharam a sua experiência com tais produtos. Mais tarde, os seguintes grupos foram chamados Grupos de Desenvolvedores do Google. GDGs podem assumir muitas formas - de apenas algumas pessoas que se juntam para assistir alguns vídeos, para grandes encontros com demonstrações, palestras técnicas, hackathons e conferências."

# Logistics Find Way Block
findWayTitle: "Encontre um caminho"
logisticsMapCenterCoordinates: "-2.1167705, -48.2805993"
logisticsMapMobileCenterCoordinates: "-2.1167705, -48.2805993"

# Logistics Direction Details Block
directionDetailsTitle: "Conheça Belém do Pará"
directionDetailsCards:
 - {title: "Bicicleta", information: 'O bicicletário é gratuito para todos aqueles que participarem do evento!'}
 - {title: "Carro", information: 'O estacionamento no local custa <strong>R$25,00</strong> a diária, mas dê preferência a carona solidária.'}
 - {title: "Transporte Público", information: 'O transporte público é a forma que mais recomendamos: <br /><ul><li><strong>Estação Jurujuba</strong> (Linha 9 – Esmeralda / Osasco-Grajaú) é a mais próxima.</li><br/> <li><strong>Vans</strong> (sinalizadas com a logo do evento) que farão o translado Estação-Senac- Estação.</li></ul>'}
directionDetailsWideCards:
 
scheduleWarning: "Observação: a programação ainda pode sofrer alterações sem aviso prévio."
